"""
Reusable Dash UI components.
"""

from dash import html, dcc
import dash_bootstrap_components as dbc


def metric_card(label: str, value: str, delta: str = None,
                delta_direction: str = None, subtitle: str = None):
    """
    Premium metric card with optional delta indicator.

    Args:
        label: Metric name (e.g., "Total Journeys").
        value: Pre-formatted metric value (e.g., "150,000").
        delta: Pre-formatted delta string (e.g., "+26.4pp").
        delta_direction: 'positive' or 'negative' for coloring.
        subtitle: Optional small text below value.
    """
    children = [
        html.Div(label, className="metric-label"),
        html.Div(value, className="metric-value"),
    ]

    if delta:
        delta_class = f"metric-delta {delta_direction or ''}"
        children.append(html.Div(delta, className=delta_class))

    if subtitle:
        children.append(html.Div(subtitle, className="metric-subtitle"))

    return html.Div(children, className="metric-card animate-in")


def insight_callout(text: str, icon: str = "💡"):
    """
    Highlighted insight callout box.
    Text should be dynamically generated by the metrics layer.
    """
    return html.Div(
        [
            html.Span(icon, className="insight-icon"),
            html.Span(text, className="insight-text"),
        ],
        className="insight-callout animate-in",
    )


def chart_container(title: str, chart_id: str, height: str = "400px"):
    """Styled container for a Plotly chart."""
    return html.Div(
        [
            html.H3(title, className="chart-title"),
            dcc.Graph(
                id=chart_id,
                style={"height": height},
                config={"displayModeBar": False},
            ),
        ],
        className="chart-container",
    )


def model_selector(available_models: list, starred_models: list = None,
                    component_id: str = "model-selector"):
    """
    Toggleable model selection pills.
    Starred models are highlighted with ★.
    """
    starred = set(starred_models or [])
    pills = []

    for model in available_models:
        display_name = model.replace("_", " ").title()
        class_name = "model-pill active"
        if model in starred:
            class_name += " starred"

        pills.append(
            html.Button(
                display_name,
                id={"type": "model-pill", "model": model},
                className=class_name,
                n_clicks=0,
            )
        )

    return html.Div(
        [
            html.Div(pills, className="model-selector-container"),
            dcc.Store(id=f"{component_id}-store", data=available_models),
        ]
    )


def section_header(title: str, subtitle: str = None):
    """Page section header with optional subtitle."""
    children = [html.H2(title, className="page-title")]
    if subtitle:
        children.append(html.P(subtitle, className="page-subtitle"))
    return html.Div(children)


def navbar():
    """Top navigation bar."""
    nav_items = [
        dbc.NavItem(dbc.NavLink("Executive Summary", href="/", active="exact")),
        dbc.NavItem(dbc.NavLink("Attribution", href="/attribution", active="exact")),
        dbc.NavItem(dbc.NavLink("Journeys", href="/journeys", active="exact")),
        dbc.NavItem(dbc.NavLink("Budget", href="/budget", active="exact")),
        dbc.NavItem(dbc.NavLink("Identity", href="/identity", active="exact")),
        dbc.NavItem(dbc.NavLink("Channels", href="/channels", active="exact")),
        dbc.NavItem(dbc.NavLink("Validation", href="/validation", active="exact")),
        dbc.NavItem(dbc.NavLink("Technical", href="/technical", active="exact")),
    ]

    return dbc.Navbar(
        dbc.Container(
            [
                html.Div(
                    [
                        html.Div("Erie Insurance", className="navbar-brand-text"),
                        html.Div("Multi-Channel Attribution Intelligence", className="navbar-brand-sub"),
                    ],
                ),
                dbc.Nav(nav_items, className="ms-auto", navbar=True),
            ],
            fluid=True,
        ),
        className="navbar-custom",
        dark=True,
    )
