"""Styled insight/finding callout boxes component."""
from dash import html


def insight_callout(text: str, icon: str = "💡"):
    """
    Highlighted insight callout box.
    Text should be dynamically generated by the metrics layer.
    """
    return html.Div(
        [
            html.Span(icon, className="insight-icon"),
            html.Span(text, className="insight-text"),
        ],
        className="insight-callout animate-in",
    )


def insight_card(title: str, text: str, severity: str = "info"):
    """
    Rich insight card with title, body, and severity coloring.

    Args:
        title: Insight headline.
        text: Detailed finding text.
        severity: 'info', 'success', 'warning', 'danger' for border color.
    """
    return html.Div(
        [
            html.H5(title, className="insight-card-title"),
            html.P(text, className="insight-card-text"),
        ],
        className=f"insight-card insight-{severity} animate-in",
    )


def key_finding(finding: str, metric_value: str = None, context: str = None):
    """
    Key finding callout for executive-level insights.

    Args:
        finding: Main finding statement.
        metric_value: Highlighted metric (displayed prominently).
        context: Additional context or comparison.
    """
    children = []
    if metric_value:
        children.append(html.Div(metric_value, className="finding-metric"))
    children.append(html.Div(finding, className="finding-text"))
    if context:
        children.append(html.Div(context, className="finding-context"))

    return html.Div(children, className="key-finding animate-in")
